service: mirko-hot-bot
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  profile: sls_framework
  region: eu-west-1
  runtime: nodejs12.x
  environment:
    appkey: d99b6pFK8f
    secretkey: z7nF82zdPy
    dynamo_table: mirko_hot_entries_24h
    region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.dynamo_table}

functions:
  hotFetcher:
    handler: handler.hotFetcher
    memorySize: 1024
    timeout: 30
    events:
      - schedule: cron(0 8,15,21 * * ? *) # (+1h for poland)

resources:
  Resources:
    HotEntriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.dynamo_table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamViewType: NEW_IMAGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
