service: mirko-hot-bot
frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  profile: sls_framework
  region: eu-west-1
  runtime: nodejs12.x
  environment:
    appkey: d99b6pFK8f
    secretkey: z7nF82zdPy
    nick: Mirkostatbot
    pass:
    dynamo_table: mirko_hot_entries_24h_rev2
    region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.dynamo_table}

functions:
  hotFetcher:
    handler: handler.hotFetcher
    memorySize: 256
    timeout: 30
    events:
      - schedule: cron(*/30 7-23 * * ? *) # (every 30th minute from 8 to 24 -> +1h for poland)
  userNotifier:
    handler: handler.userNotifier
    memorySize: 128
    timeout: 30
    events:
      - stream:
          type: dynamodb
          batchSize: 25
          enabled: true
          arn: { "Fn::GetAtt": ["HotEntriesTable", "StreamArn"] }

resources:
  Resources:
    HotEntriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.dynamo_table}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

